### ISSUE TITLE
Fix crosswalk cookoo sounders that don't sound anymore

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#122]
After the bounding box and signal upgrades that we did recently throughout most of the mod, the crosswalk cookoo sounders no longer sound. Not only those blocks don't sound anymore, there are still a few more blocks that still don't sound, such as the fair gate readers for example. I'll be taking a look into it some more but this issue still needs to be fixed eventually.

**Comment by mica-alex** [comment]
Cuckoo sounders were tested this morning, and no issues were found. The sound played as expected in the server world.
