### ISSUE TITLE
Fix blockstates on Lakewood styled light mount

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#31]
This issue still hasn’t been fixed yet as we keep on forgetting to do this.

**Comment by mica-alex** [comment]
Fix will be released to `main` as part of `dev/2023.2.1`. Addressed via commit https://github.com/Mica-Technologies/minecraft-city-super-mod/commit/e59b4c6fc0dbe75a47b73df2859b47d281f6359a.
