### ISSUE TITLE
Fix broken abstract code

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#40]
Some abstract code from one of the dev branches had made it into the abstract code of the stable branch, impacting most of the core functionality of ForgeEnergyProducer. This abstract class is needed for Forge Energy production in the infinite power block and currently half of the class has been overwritten by that very code. In a result to that, the infinite power block no longer produces any Forge Energy per tick (at absolute zero with a few stray buffers on occasion) when anything is attached to it, such as IE relays or flux plugs from Flux Networks.

**Comment by AngelWingsPanda** [comment]
This is also the same with the fire alarms also having the same broken abstract classes leaked over from the dev branches.

**Comment by AngelWingsPanda** [comment]
> Some abstract code from one of the dev branches had made it into the abstract code of the stable branch, impacting most of the core functionality of ForgeEnergyProducer. This abstract class is needed for Forge Energy production in the infinite power block and currently half of the class has been overwritten by that very code. In a result to that, the infinite power block no longer produces any Forge Energy per tick (at absolute zero with a few stray buffers on occasion) when anything is attached to it, such as IE relays or flux plugs from Flux Networks.

This block is still broken from my testing.

**Comment by mica-alex** [comment]
Abstract code has been migrated successfully and tested to contain no immediate issues or concerns.

@AngelWingsPanda If this block is still not functioning, please create a new issue describing the behavior you are or are not seeing with that specific block.
