### ISSUE TITLE
Fix  block registration on all blocks

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#48]
This is the last but rather annoying MCreator remnant that we still need to investigate further regarding block registration. This isn’t an issue for blocks that we have created back in the MCreator days that don’t have this issue, but any blocks that we have made after moving to standalone development will have this issue. Blocks that tend to have broken registrations will tend to have a bunch of problems when it comes to copying and pasting with FAWE, to blocks not appearing at all or replaced with other blocks as a placeholder.

**Comment by mica-alex** [comment]
I have confirmed that this is an issue with FAWE caching and is likely occurring with other mods using a large number of block IDs. As such, this cannot be addressed at the CSM level, and this issue will be closed.
