### ISSUE TITLE
Emergency light is broken

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#54]
Emergency lights no longer light up when redstone power is lost.

**Comment by mica-alex** [comment]
The emergency light itself is broken. There is no issue with the abstract code.

**Comment by mica-alex** [comment]
No issues were identified during testing related to the emergency light block on both client or server side. 

Placing an emergency light block and then a lever next to it results in the proper/expected on/off behavior.
