### ISSUE TITLE
Implement fence-like logic on metal poles to improve connecting/save variant IDs

### ISSUE THREAD

**Issue by mica-alex** [Mica-Technologies/minecraft-city-super-mod#55]
Implement fence-like logic on the metal poles and signal arms to allow for dynamic connecting of neighboring blocks.

The existing mount blocks will remain, and be repurposed for this, while the original pole variants will remain untouched. This provides the same interface for building poles without connection, but also improves mount/connection variants such that they can connect on any/either side without additional variants in the code itself.

**Comment by AngelWingsPanda** [comment]
This is already a WIP now as additional testing needs to be done.

**Comment by mica-alex** [comment]
## Blocks to be Exempted

These are the blocks which shall be removed, or black-listed, from the traffic pole auto-connection system.

- [ ] Crosswalk signals (They have their own mount built into the model itself)

## Blocks to be Corrected

These are blocks which shall be corrected, where the behavior of the auto-connect system must be changed to ensure expected behavior

- [ ] Traffic signal sensors (The auto-connect mount is on the wrong side of the pole due to the way sensor models are constructed)

**Comment by AngelWingsPanda** [comment]
This now has been implemented for the most part as I'm now going to be closing this issue. Feel free to reopen if we find another use for the fence like logic elsewhere in the mod in the near future.
