### ISSUE TITLE
Sort Forge block registry ID numbers for FAWE

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#56]
We still need to go through all the Forge block registry ID numbers that are currently in use with CSM and try to remap them to existing registry numbers (mods that we removed, etc.) so they can work better with FAWE. This will only be done for any new blocks that have been added into the mod recently.

**Comment by mica-alex** [comment]
This issue cannot be completed as it is not within the scope of CSM.

CSM does not contain or map block IDs. Block IDs are assigned by Forge/Minecraft itself when the world is created, when the mod is added, or when a new block is added. 

Referring to the former sort IDs from MCreator, those were not the same as block IDs. Sort IDs simply dictated the order in which blocks/items were registered. By effect, lower sort IDs were registered first and had/have lower block IDs, but they are not directly related.
