### ISSUE TITLE
Update release action to cleanup dev pre-releases after expiry time

### ISSUE THREAD

**Issue by mica-alex** [Mica-Technologies/minecraft-city-super-mod#65]
Update the release action to cleanup dev pre-releases after a defined expiry time (example: 180 days)

**Comment by AngelWingsPanda** [comment]
> Update the release action to cleanup dev pre-releases after a defined expiry time (example: 180 days)

Given how development is going to pick up eventually, I still think we should keep the influx of new dev releases to no longer than 2 weeks at least, in a similar vein to how Windows Insider builds are given. I still want to fracture in your busy work schedule, but I think that will be more than ideal.

**Comment by mica-alex** [comment]
> > Update the release action to cleanup dev pre-releases after a defined expiry time (example: 180 days)
> 
> Given how development is going to pick up eventually, I still think we should keep the influx of new dev releases to no longer than 1 to 2 weeks at least, in a similar vein to how Windows Insider builds are given. I still want to factor in your busy work schedule, but I think that will be more than ideal.

I mainly give them a longer expiry time because we sometimes use dev builds on our server. Long expiry times allows for easier active testing in mod packs, while still having the expiration to encourage the ultimate usage of a full release. Perhaps instead of 180, 90 days is better?

**Comment by AngelWingsPanda** [comment]
> > > Update the release action to cleanup dev pre-releases after a defined expiry time (example: 180 days)
> > 
> > 
> > Given how development is going to pick up eventually, I still think we should keep the influx of new dev releases to no longer than 1 to 2 weeks at least, in a similar vein to how Windows Insider builds are given. I still want to factor in your busy work schedule, but I think that will be more than ideal.
> 
> I mainly give them a longer expiry time because we sometimes use dev builds on our server. Long expiry times allows for easier active testing in mod packs, while still having the expiration to encourage the ultimate usage of a full release. Perhaps instead of 180, 90 days is better?

90 days will be more ideal.

**Comment by mica-alex** [comment]
90 days has been implemented and this will enter PR later today
