### ISSUE TITLE
Add remaining metal sets

### ISSUE THREAD

**Issue by mica-alex** [Mica-Technologies/minecraft-city-super-mod#70]
- [x] Need to commit/push new metal textures
- [x] Need to add corresponding block sets

@AngelWingsPanda not sure if you have any additional new metal textures prepped at this point, but I was thinking these new textures should be added:

- [x] Copper and/or Orange
- [x] Yellow
- [x] Light Blue
- [x] Purple
- [x] Iridescent

**Comment by AngelWingsPanda** [comment]
> * [x]  Need to commit/push new metal textures
> * [ ]  Need to add corresponding block sets
> 
> @AngelWingsPanda not sure if you have any additional new metal textures prepped at this point, but I was thinking these new textures should be added:
> 
> * [x]  Copper and/or Orange
> * [x]  Yellow
> * [x]  Light Blue
> * [x]  Purple
> * [ ]  Iridescent

All colors along with a few others are now in the `to-be-added-to-mod` folder. The one left to do now is the iridescent one, as I'm still trying to work on getting that one right.

**Comment by AngelWingsPanda** [comment]
The block sets have been added in now it seems. Still working on doing the iridescent one.

**Comment by AngelWingsPanda** [comment]
Once that is done @mica-alex, feel free to close this issue.
