### ISSUE TITLE
Add blue tape backplates for bike lanes

### ISSUE THREAD

**Issue by AngelWingsPanda** [Mica-Technologies/minecraft-city-super-mod#87]
This will be an extensive experiment fully conducted by the UIA FHWA for use solely on bike lanes and in some cases on pedestrian crosswalks. Green tape on backplates was also another option I considered a while back, but it'll be something to look into if we are still interested in adding additional backplate tape colors to the mod.

**Comment by mica-alex** [comment]
Completed in a previous release
